### ISSUE TITLE
Plugins build fails

### ISSUE THREAD

**Issue by benfab** [mesosphere/marathon-example-plugins#17]
Hello,

I am getting the following dependency issue while trying to build the plugins:

```# sbt clean pack
[info] Loading project definition from /root/marathon-example-plugins/project
[info] Set current project to plugins (in build file:/root/marathon-example-plugins/)
[success] Total time: 0 s, completed Apr 21, 2017 1:35:25 PM
[info] Updating {file:/root/marathon-example-plugins/}env...
[info] Updating {file:/root/marathon-example-plugins/}http...
[info] Resolving mesosphere.marathon#plugin-interface_2.11;1.3.5, ...
[warn]  module not found: mesosphere.marathon#plugin-interface_2.11;1.3.5,
[warn] ==== local: tried
[warn]   /root/.ivy2/local/mesosphere.marathon/plugin-interface_2.11/1.3.5,/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/mesosphere.marathon/plugin-interface_2.11/1.3.5,/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/mesosphere/marathon/plugin-interface_2.11/1.3.5,/plugin-interface_2.11-1.3.5,.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/mesosphere/marathon/plugin-interface_2.11/1.3.5,/plugin-interface_2.11-1.3.5,.pom
[warn] ==== Mesosphere Public Repo: tried
[warn]   http://downloads.mesosphere.io/maven/mesosphere/marathon/plugin-interface_2.11/1.3.5,/plugin-interface_2.11-1.3.5,.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: mesosphere.marathon#plugin-interface_2.11;1.3.5,: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          mesosphere.marathon:plugin-interface_2.11:1.3.5, (/root/marathon-example-plugins/env/build.sbt#L7-12)
[warn]            +- mesosphere.marathon:env-plugin_2.11:1.0
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] Updating {file:/root/marathon-example-plugins/}javaauth...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/root/marathon-example-plugins/}auth...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 4 Scala sources to /root/marathon-example-plugins/auth/target/scala-2.11/classes...
[info] Compiling 4 Java sources to /root/marathon-example-plugins/javaauth/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /root/marathon-example-plugins/http/target/scala-2.11/classes...
[info] Packaging /root/marathon-example-plugins/javaauth/target/scala-2.11/java-auth-plugin_2.11-1.0.jar ...
[info] Done packaging.
[info] Packaging /root/marathon-example-plugins/http/target/scala-2.11/http-plugin_2.11-1.0.jar ...
[info] Done packaging.
[info] Packaging /root/marathon-example-plugins/auth/target/scala-2.11/auth-plugin_2.11-1.0.jar ...
[info] Done packaging.
sbt.ResolveException: unresolved dependency: mesosphere.marathon#plugin-interface_2.11;1.3.5,: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:165)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] (env/*:update) sbt.ResolveException: unresolved dependency: mesosphere.marathon#plugin-interface_2.11;1.3.5,: not found
[error] Total time: 11 s, completed Apr 21, 2017 1:35:36 PM
```

**Environment:**
OS: CentOS 7
sbt version 0.13.8

**Steps to reproduce:**
`# git clone https://github.com/mesosphere/marathon-example-plugins.git`  
`# cd marathon-example-plugins`  
`# sbt clean pack` 

Do you have any ideas to fix this dependency issue?

**Comment by highbass** [comment]
change the resolver from http to https ... i have bigger problems trying to make this run in 1.9

**Comment by ror6ax** [comment]
Hi, hitting the same issue here. sbt 0.13.8 
Setting resolver to https does not change anything, sadly.
